kind: Deployment
apiVersion: apps/v1
metadata:
  name: dubbo3-consumer-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo3-consumer
  template:
    metadata:
      labels:
        app: dubbo3-consumer
        sidecar.istio.io/inject: 'true'
        version: v1
    spec:
      containers:
        - name: container-1
          image: release-ci.daocloud.io/mspider/spring-dubbo3-consumer:v0.2
          env:
            - name: PROVIDER_URL
              value: tri://dubbo3-provider:20880
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dubbo3-consumer-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo3-consumer
  template:
    metadata:
      labels:
        app: dubbo3-consumer
        sidecar.istio.io/inject: 'true'
        version: v2
    spec:
      containers:
        - name: container-1
          image: release-ci.daocloud.io/mspider/spring-dubbo3-consumer:v0.2
          env:
            - name: PROVIDER_URL
              value: tri://dubbo3-provider:20880
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dubbo3-consumer-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo3-consumer
  template:
    metadata:
      labels:
        app: dubbo3-consumer
        sidecar.istio.io/inject: 'true'
        version: v3
    spec:
      containers:
        - name: container-1
          image: release-ci.daocloud.io/mspider/spring-dubbo3-consumer:v0.2
          env:
            - name: PROVIDER_URL
              value: tri://dubbo3-provider:20880
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: dubbo3-consumer
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: dubbo3-consumer
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dubbo-consumer
spec:
  host: dubbo3-consumer
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
    - labels:
        version: v3
      name: v3
  trafficPolicy:
    connectionPool:
      http:
        maxRetries: 3
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: consumer
spec:
  gateways:
    - dubbo/dubbo
  hosts:
    - '*'
  http:
    - headers:
        request:
          add:
            lane: test-v1
      match:
        - queryParams:
            name:
              exact: test-v1
      route:
        - destination:
            host: dubbo3-consumer.dubbo.svc.cluster.local
            port:
              number: 8080
            subset: v1
    - headers:
        request:
          add:
            lane: test-v2
      match:
        - queryParams:
            name:
              exact: test-v2
      route:
        - destination:
            host: dubbo3-consumer.dubbo.svc.cluster.local
            port:
              number: 8080
            subset: v2
    - headers:
        request:
          add:
            lane: test-v3
      match:
        - queryParams:
            name:
              exact: test-v3
      route:
        - destination:
            host: dubbo3-consumer.dubbo.svc.cluster.local
            port:
              number: 8080
            subset: v3
    - route:
        - destination:
            host: dubbo3-consumer.dubbo.svc.cluster.local
            port:
              number: 8080
            subset: v1