---
kind: Rollout
apiVersion: argoproj.io/v1alpha1
metadata:
  name: dubbo3-provider-v1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo3-provider
  template:
    metadata:
      labels:
        app: dubbo3-provider
        sidecar.istio.io/inject: "true"
        version: v1
    spec:
      containers:
        - name: container-1
          image: release-ci.daocloud.io/mspider/spring-dubbo3-provider:v0.2
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: provider
            routes:
              - test-v1
          destinationRule:
            name: dubbo-provider
            stableSubsetName: stable
            canarySubsetName: canary
      steps:
        - setWeight: 5
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 10m
---
kind: Service
apiVersion: v1
metadata:
  name: dubbo3-provider
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  ports:
    - name: grpc-20880
      protocol: TCP
      port: 20880
      targetPort: 20880
  selector:
    app: dubbo3-provider
  type: ClusterIP

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: provider
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  gateways:
    - mesh
  hosts:
    - dubbo3-provider
  http:
    - name: test-v1
      match:
        - headers:
            lane:
              exact: test-v1
      route:
        - destination:
            host: dubbo3-provider
            port:
              number: 20880
            subset: stable
          weight: 100
        - destination:
            host: dubbo3-provider
            port:
              number: 20880
            subset: canary
          weight: 0
    - route:
        - destination:
            host: dubbo3-provider
            port:
              number: 20880
            subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dubbo-provider
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  host: dubbo3-provider
  subsets:
    - labels:
        app: dubbo3-provider
      name: stable
    - labels:
        app: dubbo3-provider
      name: canary
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10000